//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emerde.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emerde.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Room.
        /// </summary>
        public static string AddRoom {
            get {
                return ResourceManager.GetString("AddRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The live room {0} has been added.
        /// </summary>
        public static string AddRoomErrorDuplicated {
            get {
                return ResourceManager.GetString("AddRoomErrorDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add it directly without detecting validity.
        /// </summary>
        public static string AddRoomForce {
            get {
                return ResourceManager.GetString("AddRoomForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added {0} live room.
        /// </summary>
        public static string AddRoomSucc {
            get {
                return ResourceManager.GetString("AddRoomSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance Settings.
        /// </summary>
        public static string AppearanceSettings {
            get {
                return ResourceManager.GetString("AppearanceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Shutdown.
        /// </summary>
        public static string AutoShutdown {
            get {
                return ResourceManager.GetString("AutoShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto shutdown when unrecording.
        /// </summary>
        public static string AutoShutdownHint {
            get {
                return ResourceManager.GetString("AutoShutdownHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System will be auto shutdown in 1 minute.
        /// </summary>
        public static string AutoShutdownInTime {
            get {
                return ResourceManager.GetString("AutoShutdownInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Shutdown Time (HH:MM).
        /// </summary>
        public static string AutoShutdownTime {
            get {
                return ResourceManager.GetString("AutoShutdownTime", resourceCulture);
            }
        }

        public static string AutoShutdownAfterTranscode {
            get { return ResourceManager.GetString("AutoShutdownAfterTranscode", resourceCulture); }
        }

        public static string AutoShutdownComputer {
            get { return ResourceManager.GetString("AutoShutdownComputer", resourceCulture); }
        }

        public static string AutoShutdownCancel {
            get { return ResourceManager.GetString("AutoShutdownCancel", resourceCulture); }
        }

        public static string AutoShutdownNow {
            get { return ResourceManager.GetString("AutoShutdownNow", resourceCulture); }
        }

        public static string AutoShutdownAfterTranscodeNow {
            get { return ResourceManager.GetString("AutoShutdownAfterTranscodeNow", resourceCulture); }
        }

        public static string ButtonOfAcknowledge {
            get { return ResourceManager.GetString("ButtonOfAcknowledge", resourceCulture); }
        }

        public static string AutoShutdownComputerDescription {
            get { return ResourceManager.GetString("AutoShutdownComputerDescription", resourceCulture); }
        }

        public static string AutoShutdownApplicationDescription {
            get { return ResourceManager.GetString("AutoShutdownApplicationDescription", resourceCulture); }
        }

        public static string AutoShutdownComputerFailed {
            get { return ResourceManager.GetString("AutoShutdownComputerFailed", resourceCulture); }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ButtonOfAdd {
            get {
                return ResourceManager.GetString("ButtonOfAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonOfCancel {
            get {
                return ResourceManager.GetString("ButtonOfCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonOfClose {
            get {
                return ResourceManager.GetString("ButtonOfClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Now.
        /// </summary>
        public static string ButtonOfCreateNow {
            get {
                return ResourceManager.GetString("ButtonOfCreateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto.
        /// </summary>
        public static string ButtonOfGoto {
            get {
                return ResourceManager.GetString("ButtonOfGoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t show again.
        /// </summary>
        public static string ButtonOfOffRemind {
            get {
                return ResourceManager.GetString("ButtonOfOffRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string ButtonOfPlay {
            get {
                return ResourceManager.GetString("ButtonOfPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ButtonOfSettings {
            get {
                return ResourceManager.GetString("ButtonOfSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string CheckConnectivity {
            get {
                return ResourceManager.GetString("CheckConnectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running in the background.
        /// </summary>
        public static string CloseToTrayHint {
            get {
                return ResourceManager.GetString("CloseToTrayHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string CreateDesktopShortcut {
            get {
                return ResourceManager.GetString("CreateDesktopShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Desktop Shortcut.
        /// </summary>
        public static string CreateDesktopShortcutHint {
            get {
                return ResourceManager.GetString("CreateDesktopShortcutHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No live room added~.
        /// </summary>
        public static string EmptyRoomHint {
            get {
                return ResourceManager.GetString("EmptyRoomHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Recording.
        /// </summary>
        public static string EnableRecord {
            get {
                return ResourceManager.GetString("EnableRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether live streaming recording is enabled.
        /// </summary>
        public static string EnableRecordHint {
            get {
                return ResourceManager.GetString("EnableRecordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter room URL.
        /// </summary>
        public static string EnterRoomUrl {
            get {
                return ResourceManager.GetString("EnterRoomUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect live room URL.
        /// </summary>
        public static string ErrorRoomUrl {
            get {
                return ResourceManager.GetString("ErrorRoomUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        public static string FailOp {
            get {
                return ResourceManager.GetString("FailOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get information about the live room.
        /// </summary>
        public static string GetRoomInfoError {
            get {
                return ResourceManager.GetString("GetRoomInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Live Room.
        /// </summary>
        public static string GotoLiveRoom {
            get {
                return ResourceManager.GetString("GotoLiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to get it?.
        /// </summary>
        public static string HowToGet {
            get {
                return ResourceManager.GetString("HowToGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Windows System Awake.
        /// </summary>
        public static string KeepActiveHint {
            get {
                return ResourceManager.GetString("KeepActiveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Awake.
        /// </summary>
        public static string KeepAwake {
            get {
                return ResourceManager.GetString("KeepAwake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default follows the system language.
        /// </summary>
        public static string LanguageHint {
            get {
                return ResourceManager.GetString("LanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Notification.
        /// </summary>
        public static string LiveNotification {
            get {
                return ResourceManager.GetString("LiveNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to notify the start of the streaming through Windows system notifications, etc.
        /// </summary>
        public static string LiveNotificationHint {
            get {
                return ResourceManager.GetString("LiveNotificationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto goto Live Room.
        /// </summary>
        public static string LiveNotificationToGotoLiveRoom {
            get {
                return ResourceManager.GetString("LiveNotificationToGotoLiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto mute.
        /// </summary>
        public static string LiveNotificationToGotoLiveRoomAndMute {
            get {
                return ResourceManager.GetString("LiveNotificationToGotoLiveRoomAndMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification via E-mail.
        /// </summary>
        public static string LiveNotificationToMail {
            get {
                return ResourceManager.GetString("LiveNotificationToMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification via playing music.
        /// </summary>
        public static string LiveNotificationToPlayMusic {
            get {
                return ResourceManager.GetString("LiveNotificationToPlayMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use built-in music or specify music file path.
        /// </summary>
        public static string LiveNotificationToPlayMusicPath {
            get {
                return ResourceManager.GetString("LiveNotificationToPlayMusicPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification via Windows System.
        /// </summary>
        public static string LiveNotificationToSystem {
            get {
                return ResourceManager.GetString("LiveNotificationToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Preview.
        /// </summary>
        public static string LivePreview {
            get {
                return ResourceManager.GetString("LivePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview error.
        /// </summary>
        public static string LivePreviewError {
            get {
                return ResourceManager.GetString("LivePreviewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a live room to preview.
        /// </summary>
        public static string LivePreviewIdle {
            get {
                return ResourceManager.GetString("LivePreviewIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previewing.
        /// </summary>
        public static string LivePreviewPlaying {
            get {
                return ResourceManager.GetString("LivePreviewPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to preview.
        /// </summary>
        public static string LivePreviewReady {
            get {
                return ResourceManager.GetString("LivePreviewReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No live preview stream available.
        /// </summary>
        public static string LivePreviewUnavailable {
            get {
                return ResourceManager.GetString("LivePreviewUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Cookie.
        /// </summary>
        public static string NoCookie {
            get {
                return ResourceManager.GetString("NoCookie", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Platform Access.
        /// </summary>
        public static string PlatformAccess {
            get {
                return ResourceManager.GetString("PlatformAccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Proxy applies to platform requests and preview playback when enabled..
        /// </summary>
        public static string ProxyAppliesToPlatformRequests {
            get {
                return ResourceManager.GetString("ProxyAppliesToPlatformRequests", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supported.
        /// </summary>
        public static string Supported {
            get {
                return ResourceManager.GetString("Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Room.
        /// </summary>
        public static string LiveRoom {
            get {
                return ResourceManager.GetString("LiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Running Settings.
        /// </summary>
        public static string LongRunningSettings {
            get {
                return ResourceManager.GetString("LongRunningSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto {0}&apos;s live room immediately.
        /// </summary>
        public static string MailBodyElement {
            get {
                return ResourceManager.GetString("MailBodyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Settings.
        /// </summary>
        public static string NetworkSettings {
            get {
                return ResourceManager.GetString("NetworkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no recording tasks.
        /// </summary>
        public static string NoRecordTask {
            get {
                return ResourceManager.GetString("NoRecordTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not supported in recording mode.
        /// </summary>
        public static string NotSupportedOnRecording {
            get {
                return ResourceManager.GetString("NotSupportedOnRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File ffplay not found so cannot be played!.
        /// </summary>
        public static string PlayerErrorOfFFplayNotFound {
            get {
                return ResourceManager.GetString("PlayerErrorOfFFplayNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No playable recording file.
        /// </summary>
        public static string PlayerErrorOfNoFile {
            get {
                return ResourceManager.GetString("PlayerErrorOfNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in player.
        /// </summary>
        public static string PlayerInner {
            get {
                return ResourceManager.GetString("PlayerInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FFplay player.
        /// </summary>
        public static string PlayerInnerHint {
            get {
                return ResourceManager.GetString("PlayerInnerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable reacangle window.
        /// </summary>
        public static string PlayerInnerUseRect {
            get {
                return ResourceManager.GetString("PlayerInnerUseRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System player.
        /// </summary>
        public static string PlayerSystem {
            get {
                return ResourceManager.GetString("PlayerSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use System player.
        /// </summary>
        public static string PlayerSystemHint {
            get {
                return ResourceManager.GetString("PlayerSystemHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Recording.
        /// </summary>
        public static string PlayRecord {
            get {
                return ResourceManager.GetString("PlayRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support to play the recording videos.
        /// </summary>
        public static string PlayRecordHint {
            get {
                return ResourceManager.GetString("PlayRecordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PreviewLiveRoom {
            get {
                return ResourceManager.GetString("PreviewLiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy URL cannot be empty.
        /// </summary>
        public static string ProxyErrorOfEmptyUrl {
            get {
                return ResourceManager.GetString("ProxyErrorOfEmptyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid proxy or request failed: {0}.
        /// </summary>
        public static string ProxyErrorOfExceptionMessage {
            get {
                return ResourceManager.GetString("ProxyErrorOfExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy URL is malformed.
        /// </summary>
        public static string ProxyErrorOfFormat {
            get {
                return ResourceManager.GetString("ProxyErrorOfFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy URL host format is incorrect.
        /// </summary>
        public static string ProxyErrorOfHostFormatError {
            get {
                return ResourceManager.GetString("ProxyErrorOfHostFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy URL missing hostname or port number.
        /// </summary>
        public static string ProxyErrorOfMissHostOrPort {
            get {
                return ResourceManager.GetString("ProxyErrorOfMissHostOrPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy URL port number format is incorrect.
        /// </summary>
        public static string ProxyErrorOfPortFormatError {
            get {
                return ResourceManager.GetString("ProxyErrorOfPortFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy URL port number out of range.
        /// </summary>
        public static string ProxyErrorOfPortOutOfRange {
            get {
                return ResourceManager.GetString("ProxyErrorOfPortOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name and port number.
        /// </summary>
        public static string ProxyHostAndPort {
            get {
                return ResourceManager.GetString("ProxyHostAndPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy available, response status code {0}.
        /// </summary>
        public static string ProxySuccOfStatusCode {
            get {
                return ResourceManager.GetString("ProxySuccOfStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Format.
        /// </summary>
        public static string RecordFormat {
            get {
                return ResourceManager.GetString("RecordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to auto delete the original TS/FLV file after converting the format.
        /// </summary>
        public static string RecordFormatAutoRemove {
            get {
                return ResourceManager.GetString("RecordFormatAutoRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ensure stable recording, only supports TS/FLV or will be auto converted later.
        /// </summary>
        public static string RecordFormatHint {
            get {
                return ResourceManager.GetString("RecordFormatHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Log.
        /// </summary>
        public static string RecordLog {
            get {
                return ResourceManager.GetString("RecordLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Settings.
        /// </summary>
        public static string RecordSettings {
            get {
                return ResourceManager.GetString("RecordSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Status.
        /// </summary>
        public static string RecordStatus {
            get {
                return ResourceManager.GetString("RecordStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string RecordStatusOfDisabled {
            get {
                return ResourceManager.GetString("RecordStatusOfDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string RecordStatusOfError {
            get {
                return ResourceManager.GetString("RecordStatusOfError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized.
        /// </summary>
        public static string RecordStatusOfInitialized {
            get {
                return ResourceManager.GetString("RecordStatusOfInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Recording.
        /// </summary>
        public static string RecordStatusOfNotRecording {
            get {
                return ResourceManager.GetString("RecordStatusOfNotRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string RecordStatusOfRecording {
            get {
                return ResourceManager.GetString("RecordStatusOfRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string RecordStatusOfUnknown {
            get {
                return ResourceManager.GetString("RecordStatusOfUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Room.
        /// </summary>
        public static string RemoveRoom {
            get {
                return ResourceManager.GetString("RemoveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Period.
        /// </summary>
        public static string RoutineInterval {
            get {
                return ResourceManager.GetString("RoutineInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cycle period (ms) for detecting the status and other actions.
        /// </summary>
        public static string RoutineIntervalHint {
            get {
                return ResourceManager.GetString("RoutineIntervalHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down Room.
        /// </summary>
        public static string RowDownRoom {
            get {
                return ResourceManager.GetString("RowDownRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up Room.
        /// </summary>
        public static string RowUpRoom {
            get {
                return ResourceManager.GetString("RowUpRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Folder.
        /// </summary>
        public static string SaveFolder {
            get {
                return ResourceManager.GetString("SaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the saving directory distinguished by authors.
        /// </summary>
        public static string SaveFolderDistinguishedByAuthors {
            get {
                return ResourceManager.GetString("SaveFolderDistinguishedByAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the saving directory of recorded videos.
        /// </summary>
        public static string SaveFolderHint {
            get {
                return ResourceManager.GetString("SaveFolderHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Segment.
        /// </summary>
        public static string Segment {
            get {
                return ResourceManager.GetString("Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the length of time (in seconds) for each output video.
        /// </summary>
        public static string SegmentHint {
            get {
                return ResourceManager.GetString("SegmentHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Segment Time (sec).
        /// </summary>
        public static string SegmentTime {
            get {
                return ResourceManager.GetString("SegmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings File.
        /// </summary>
        public static string SettingsFile {
            get {
                return ResourceManager.GetString("SettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Settings.
        /// </summary>
        public static string SingleSettings {
            get {
                return ResourceManager.GetString("SingleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string StatusOff {
            get {
                return ResourceManager.GetString("StatusOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string StatusOn {
            get {
                return ResourceManager.GetString("StatusOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        public static string StopRecord {
            get {
                return ResourceManager.GetString("StopRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Streaming Status.
        /// </summary>
        public static string StreamStatus {
            get {
                return ResourceManager.GetString("StreamStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string StreamStatusOfDisabled {
            get {
                return ResourceManager.GetString("StreamStatusOfDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized.
        /// </summary>
        public static string StreamStatusOfInitialized {
            get {
                return ResourceManager.GetString("StreamStatusOfInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Streaming.
        /// </summary>
        public static string StreamStatusOfNotStreaming {
            get {
                return ResourceManager.GetString("StreamStatusOfNotStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming.
        /// </summary>
        public static string StreamStatusOfStreaming {
            get {
                return ResourceManager.GetString("StreamStatusOfStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string StreamStatusOfUnknown {
            get {
                return ResourceManager.GetString("StreamStatusOfUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successful.
        /// </summary>
        public static string SuccOp {
            get {
                return ResourceManager.GetString("SuccOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording is in progress. Are you sure you want to continue your operation?.
        /// </summary>
        public static string SureOnRecording {
            get {
                return ResourceManager.GetString("SureOnRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} live room?.
        /// </summary>
        public static string SureRemoveRoom {
            get {
                return ResourceManager.GetString("SureRemoveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it stop the recording of {0}?.
        /// </summary>
        public static string SureStopRecord {
            get {
                return ResourceManager.GetString("SureStopRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Color.
        /// </summary>
        public static string ThemeColor {
            get {
                return ResourceManager.GetString("ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a theme color you like.
        /// </summary>
        public static string ThemeColorHint {
            get {
                return ResourceManager.GetString("ThemeColorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeOfDarkMode {
            get {
                return ResourceManager.GetString("ThemeOfDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeOfLightMode {
            get {
                return ResourceManager.GetString("ThemeOfLightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emerde.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string TrackingSystem {
            get {
                return ResourceManager.GetString("TrackingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Run (&amp;A).
        /// </summary>
        public static string TrayMenuAutoRun {
            get {
                return ResourceManager.GetString("TrayMenuAutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit (&amp;E).
        /// </summary>
        public static string TrayMenuExit {
            get {
                return ResourceManager.GetString("TrayMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings (&amp;S).
        /// </summary>
        public static string TrayMenuOpenSettings {
            get {
                return ResourceManager.GetString("TrayMenuOpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart (&amp;R).
        /// </summary>
        public static string TrayMenuRestart {
            get {
                return ResourceManager.GetString("TrayMenuRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show (&amp;V).
        /// </summary>
        public static string TrayMenuShowMainWindow {
            get {
                return ResourceManager.GetString("TrayMenuShowMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray Icon.
        /// </summary>
        public static string TrayStatus {
            get {
                return ResourceManager.GetString("TrayStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable tray icon is following to recording status.
        /// </summary>
        public static string TrayStatusHint {
            get {
                return ResourceManager.GetString("TrayStatusHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Level.
        /// </summary>
        public static string SavePathLevel {
            get {
                return ResourceManager.GetString("SavePathLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save folder only.
        /// </summary>
        public static string SavePathLevelRootOnly {
            get {
                return ResourceManager.GetString("SavePathLevelRootOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string SavePathLevelAuthor {
            get {
                return ResourceManager.GetString("SavePathLevelAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author / Year / Month.
        /// </summary>
        public static string SavePathLevelAuthorYearMonth {
            get {
                return ResourceManager.GetString("SavePathLevelAuthorYearMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author / Year / Month / Date.
        /// </summary>
        public static string SavePathLevelAuthorDate {
            get {
                return ResourceManager.GetString("SavePathLevelAuthorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming Rule.
        /// </summary>
        public static string SaveNamingRule {
            get {
                return ResourceManager.GetString("SaveNamingRule", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto Cleanup.
        /// </summary>
        public static string DataRetention {
            get {
                return ResourceManager.GetString("DataRetention", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Automatically delete expired recording files in the save folder.
        /// </summary>
        public static string DataRetentionHint {
            get {
                return ResourceManager.GetString("DataRetentionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author_Record time.
        /// </summary>
        public static string SaveNamingRuleAuthorRecordTime {
            get {
                return ResourceManager.GetString("SaveNamingRuleAuthorRecordTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record time_Author.
        /// </summary>
        public static string SaveNamingRuleRecordTimeAuthor {
            get {
                return ResourceManager.GetString("SaveNamingRuleRecordTimeAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string SaveNamingRuleAuthor {
            get {
                return ResourceManager.GetString("SaveNamingRuleAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform_Author_Record time.
        /// </summary>
        public static string SaveNamingRulePlatformAuthorRecordTime {
            get {
                return ResourceManager.GetString("SaveNamingRulePlatformAuthorRecordTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Rule.
        /// </summary>
        public static string CustomRule {
            get {
                return ResourceManager.GetString("CustomRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete last.
        /// </summary>
        public static string DeleteLast {
            get {
                return ResourceManager.GetString("DeleteLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string TokenAuthor {
            get {
                return ResourceManager.GetString("TokenAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record time.
        /// </summary>
        public static string TokenRecordTime {
            get {
                return ResourceManager.GetString("TokenRecordTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TokenDate {
            get {
                return ResourceManager.GetString("TokenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string TokenTime {
            get {
                return ResourceManager.GetString("TokenTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using built-in player.
        /// </summary>
        public static string PreviewBuiltInPlayerHint {
            get {
                return ResourceManager.GetString("PreviewBuiltInPlayerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic Platforms.
        /// </summary>
        public static string DomesticCookiePlatforms {
            get {
                return ResourceManager.GetString("DomesticCookiePlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overseas Platforms.
        /// </summary>
        public static string OverseasCookiePlatforms {
            get {
                return ResourceManager.GetString("OverseasCookiePlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No-cookie Platforms.
        /// </summary>
        public static string NoCookiePlatforms {
            get {
                return ResourceManager.GetString("NoCookiePlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rooms / {1} live / {2} platforms.
        /// </summary>
        public static string PlatformSummaryFormat {
            get {
                return ResourceManager.GetString("PlatformSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Cookie.
        /// </summary>
        public static string UseCookie {
            get {
                return ResourceManager.GetString("UseCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank to send no cookies.
        /// </summary>
        public static string UseCookieEnterHint {
            get {
                return ResourceManager.GetString("UseCookieEnterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some platforms require cookies.
        /// </summary>
        public static string UseCookieHint {
            get {
                return ResourceManager.GetString("UseCookieHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Cookie.
        /// </summary>
        public static string UseCookieOfDouyin {
            get {
                return ResourceManager.GetString("UseCookieOfDouyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overseas Cookie.
        /// </summary>
        public static string UseCookieOfOversea {
            get {
                return ResourceManager.GetString("UseCookieOfOversea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Proxy.
        /// </summary>
        public static string UseProxy {
            get {
                return ResourceManager.GetString("UseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify your web proxy URL.
        /// </summary>
        public static string UseProxyHint {
            get {
                return ResourceManager.GetString("UseProxyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser UserAgent.
        /// </summary>
        public static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank to use the built-in browser UserAgent.
        /// </summary>
        public static string UserAgentEnterHint {
            get {
                return ResourceManager.GetString("UserAgentEnterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use a custom browser UserAgent.
        /// </summary>
        public static string UserAgentHint {
            get {
                return ResourceManager.GetString("UserAgentHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }

        public static string VideoListTitle {
            get { return ResourceManager.GetString("VideoListTitle", resourceCulture); }
        }

        public static string RefreshButton {
            get { return ResourceManager.GetString("RefreshButton", resourceCulture); }
        }

        public static string ImportFolder {
            get { return ResourceManager.GetString("ImportFolder", resourceCulture); }
        }

        public static string MergeVideos {
            get { return ResourceManager.GetString("MergeVideos", resourceCulture); }
        }

        public static string DeleteButton {
            get { return ResourceManager.GetString("DeleteButton", resourceCulture); }
        }

        public static string MoveButton {
            get { return ResourceManager.GetString("MoveButton", resourceCulture); }
        }

        public static string CopyButton {
            get { return ResourceManager.GetString("CopyButton", resourceCulture); }
        }

        public static string SelectAll {
            get { return ResourceManager.GetString("SelectAll", resourceCulture); }
        }

        public static string InvertSelection {
            get { return ResourceManager.GetString("InvertSelection", resourceCulture); }
        }

        public static string MultiSelect {
            get { return ResourceManager.GetString("MultiSelect", resourceCulture); }
        }

        public static string StreamerLabel {
            get { return ResourceManager.GetString("StreamerLabel", resourceCulture); }
        }

        public static string TimeRangeLabel {
            get { return ResourceManager.GetString("TimeRangeLabel", resourceCulture); }
        }

        public static string OpenVideo {
            get { return ResourceManager.GetString("OpenVideo", resourceCulture); }
        }

        public static string TranscodeVideo {
            get { return ResourceManager.GetString("TranscodeVideo", resourceCulture); }
        }

        public static string SplitButton {
            get { return ResourceManager.GetString("SplitButton", resourceCulture); }
        }

        public static string SplitVideo {
            get { return ResourceManager.GetString("SplitVideo", resourceCulture); }
        }

        public static string SplitInterval {
            get { return ResourceManager.GetString("SplitInterval", resourceCulture); }
        }

        public static string Minutes {
            get { return ResourceManager.GetString("Minutes", resourceCulture); }
        }

        public static string Seconds {
            get { return ResourceManager.GetString("Seconds", resourceCulture); }
        }

        public static string Hours {
            get { return ResourceManager.GetString("Hours", resourceCulture); }
        }

        public static string StartButton {
            get { return ResourceManager.GetString("StartButton", resourceCulture); }
        }

        public static string QualityLabel {
            get { return ResourceManager.GetString("QualityLabel", resourceCulture); }
        }

        public static string QualitySelectionHint {
            get { return ResourceManager.GetString("QualitySelectionHint", resourceCulture); }
        }

        public static string PreviewPause {
            get { return ResourceManager.GetString("PreviewPause", resourceCulture); }
        }

        public static string PreviewMute {
            get { return ResourceManager.GetString("PreviewMute", resourceCulture); }
        }

        public static string PreviewUnmute {
            get { return ResourceManager.GetString("PreviewUnmute", resourceCulture); }
        }

        public static string PreviewFullScreen {
            get { return ResourceManager.GetString("PreviewFullScreen", resourceCulture); }
        }

        public static string PreviewRestore {
            get { return ResourceManager.GetString("PreviewRestore", resourceCulture); }
        }

        public static string StartupAboutNoticeTitle {
            get { return ResourceManager.GetString("StartupAboutNoticeTitle", resourceCulture); }
        }

        public static string StartupAboutNoticeDescription {
            get { return ResourceManager.GetString("StartupAboutNoticeDescription", resourceCulture); }
        }
    }
}
