<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows7.0</TargetFramework>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <SelfContained>true</SelfContained>
        <PublishSingleFile>true</PublishSingleFile>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
        <PublishTrimmed>true</PublishTrimmed>
        <TrimMode>full</TrimMode>
        <PublishReadyToRun>false</PublishReadyToRun>
        <InvariantGlobalization>true</InvariantGlobalization>
        <StripSymbols>true</StripSymbols>
        <OptimizationPreference>Size</OptimizationPreference>
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <AssemblyName>Emerde.Cleanup</AssemblyName>
        <RootNamespace>Emerde.Cleanup</RootNamespace>
        <Product>Emerde Cleanup</Product>
        <AssemblyVersion>1.6.7.2</AssemblyVersion>
        <FileVersion>1.6.7.2</FileVersion>
        <Version>1.6.7.2</Version>
    </PropertyGroup>
</Project>
