<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <Platforms>x64</Platforms>
        <SelfContained>false</SelfContained>
        <PublishSingleFile>true</PublishSingleFile>
        <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
        <PublishTrimmed>false</PublishTrimmed>
        <PublishReadyToRun>false</PublishReadyToRun>
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <AppHostRelativeDotNet>..\runtime</AppHostRelativeDotNet>
        <AppHostDotNetSearch>AppRelative</AppHostDotNetSearch>
        <SatelliteResourceLanguages>en;zh-Hans;zh-Hant;ja</SatelliteResourceLanguages>
        <ApplicationIcon>..\Emerde\Assets\Installer.ico</ApplicationIcon>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AssemblyName>Emerde.Installer</AssemblyName>
        <RootNamespace>Emerde.Installer</RootNamespace>
        <Product>Emerde Installer</Product>
        <AssemblyVersion>1.6.7.1</AssemblyVersion>
        <FileVersion>1.6.7.1</FileVersion>
        <Version>1.6.7.1</Version>
    </PropertyGroup>

    <ItemGroup>
        <Resource Include="..\Emerde\Assets\Installer.png" Link="Assets\Installer.png" />
        <Resource Include="..\Emerde\Assets\Maintenance.png" Link="Assets\Maintenance.png" />
        <Resource Include="..\Emerde\Assets\Uninstaller.png" Link="Assets\Uninstaller.png" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SharpCompress" Version="0.50.0" />
        <PackageReference Include="WPF-UI" Version="4.0.3" />
    </ItemGroup>
</Project>
