name: build

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: cd src\Emerde && dotnet restore Emerde.csproj -p:Platform=x64

      - name: Build
        run: cd src\Emerde && dotnet build Emerde.csproj --configuration Release -p:Platform=x64 --no-restore

      - name: Test
        run: dotnet test Emerde.sln --configuration Release -p:Platform=x64
